### ISSUE TITLE
Does this project work on both ARM64 and x86_64 Linux based OS's?

### ISSUE THREAD

**Issue by TehDomic** [mafredri/magic4linux#3]
Would be cool to run it on Raspberry Pi and possibly on Android TV somehow too.

**Comment by mafredri** [comment]
Should work fine. You just need to have Go installed on any device (your computer is fine) and follow the [Building for other platforms](https://github.com/mafredri/magic4linux#building-for-other-platforms) and just move the binary over to your rPi (or build on the rPi directly).

Depending on which Raspberry Pi, you may need to change to `GOARCH=arm` (and set `GOARM=x`): https://github.com/golang/go/wiki/GoArm

(I don't know anything about running this on Android though, that probably won't work.)

**Comment by TehDomic** [comment]
Thanks, I'll let you know if I get anything else to work. :) (Termux has access to Go packages)

**Comment by martyfrits** [comment]
Perhaps could the microphone be utilized too?
