### ISSUE TITLE
Could the remote's microphone be utilized as well?

### ISSUE THREAD

**Issue by martyfrits** [mafredri/magic4linux#5]

**Comment by mafredri** [comment]
I would say no, for two main reasons:

1. It's not supported by [Wouterdek/magic4pc](https://github.com/Wouterdek/magic4pc)
2. It's unclear if we could do it without a rooted TV

What would you do with it? Assuming you could, would you stream the audio from remote -> magic4linux and try to do some voice recognition on the stream? How would we expose that in a way that you can build around? As for magic4linux, I don't think we should add any voice recognition logic into the service itself.

I'll close this now, but if you feel there is more to discuss around this topic, feel free.
