### ISSUE TITLE
Use behind a firewall

### ISSUE THREAD

**Issue by rotdrop** [mafredri/magic4linux#7]
Is there a known setting how to configure the firewall to make this work -- without turning the firewall off?

Thank you!

**Comment by mafredri** [comment]
Only these two UDP ports are used: https://github.com/mafredri/magic4linux/blob/ccfe1c2ba80c023dc88ba4bb03df259ac6774a84/cmd/magic4linux/main.go#L19-L20

Allow incoming on broadcast and outgoing on subscription ports should be enough, I'd venture.
